
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

    
zuul:
  ignoredServices: "*"
  routes:
    authentication-service:  
      sensitiveHeaders:
      path: /auth/**
      stripPrefix: false
      serviceId: authentication-service