spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/configuration?useSSL=false'
  cloud:
    config:
      server:
        jdbc:
          sql: 'SELECT properties.key, properties.value from  PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?'
  username: root
  password: root